//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerWebAdmin {
    
    
    public partial class CreateStoredProcedure {
        
        /// <summary>
        /// HelpLogout control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SqlServerWebAdmin.Toolbars.helplogouttoolbar HelpLogout;
        
        /// <summary>
        /// ServerLocation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SqlServerWebAdmin.Toolbars.serverlocation ServerLocation;
        
        /// <summary>
        /// DatabaseLocation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SqlServerWebAdmin.Toolbars.databaselocation DatabaseLocation;
        
        /// <summary>
        /// ServerToolbar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SqlServerWebAdmin.Toolbars.servertoolbar ServerToolbar;
        
        /// <summary>
        /// DatabaseToolbar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SqlServerWebAdmin.Toolbars.databasetoolbar DatabaseToolbar;
        
        /// <summary>
        /// SProcNameTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox SProcNameTextBox;
        
        /// <summary>
        /// CreateNewSProcButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button CreateNewSProcButton;
        
        /// <summary>
        /// SProcNameRequiredValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator SProcNameRequiredValidator;
        
        /// <summary>
        /// ErrorCreatingLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ErrorCreatingLabel;
    }
}
